spring.datasource.url=jdbc:mysql://localhost:3306/store24hdb
spring.datasource.username=store24hdbuser
spring.datasource.password=78f77cfc780794aA#
spring.jpa.hibernate.ddl-auto=update

server.address=0.0.0.0
server.port: 8443
#server.ssl.key-store:/etc/letsencrypt/live/digitalapc.xyz/keystore.p12
#server.ssl.key-store-password: 78f77cfc780794aA#
#server.ssl.keyStoreType: PKCS12
#server.ssl.keyAlias: tomcat

#security.require-ssl=true

#JWT
forum.jwt.expiration=86400000
forum.jwt.secret=S@%wHsqyaB4%t#nwgf#xtdpK%5wsPMkodc#uKzWBDc&5zzJxH^
